local module = {
    { id = 1, characteristic = "Male" },
    { id = 2, characteristic = "Female" },
    { id = 3, characteristic = "Brown hair" },
    { id = 4, characteristic = "White skin" },
    { id = 5, characteristic = "Black skin" },
    { id = 6, characteristic = "Bald" },
    { id = 7, characteristic = "Old" },
    { id = 8, characteristic = "Young" },
    { id = 9, characteristic = "With glasses" },
    { id = 10, characteristic = "Black hair" },
}


return module
