local quizQuestions = {
    {
        theme = "Food",
        questions = {
            {
                question = "Which fruit is yellow and curved?",
                answers = {"Banana", "Apple", "Grape", "Tomato"},
                correctAnswer = "Banana",
                imageId = 12508160460 
            },
            {
                question = "Which food is made from milk?",
                answers = {"Cheese", "Bread", "Pasta", "Rice"},
                correctAnswer = "Cheese",
                imageId = 4384648475
                
            }
        }
    },

    {
        theme = "Animals",
        questions = {
            {
                question = "Which animal barks?",
                answers = {"Dog", "Cat", "Bird", "Fish"},
                correctAnswer = "Dog",
                imageId = 100955803077127
            }
        }
    }
}

return quizQuestions
